### ISSUE TITLE
Error Controller

### ISSUE THREAD

**Issue by born-tocode** [kirg-projects/RLS#66]
Zaimplementuj error controller z mappingiem na /error który prezentowałby błędy w formacie przyjaznym dla użytkownika. Zapoznaj się z dokumentacją springa jak przetwarzane są błędy.

**Comment by waldemarmozola16** [comment]
Utworzyłem swój branch o nazwie 66-Error-controller.

**Comment by waldemarmozola16** [comment]
Zamykam bo mamy zajac sie uslugami do sklepu.
